apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-k8s-ci-sample
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: jenkins-k8s-ci-sample
    spec:
      containers:
      - image: neverforget/jenkins-k8s-ci-sample:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-k8s-ci-sample
        env:
        - name: branch
          value: <BRANCH_NAME>